version: '3.5'

services:
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - wp-data:/var/www/html
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env

volumes:
  wp-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wp-data
  db-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db-data

networks:
  inception:
    driver: bridge
