version: '3.5'

services:
  mariadb:
    container_name: mariadb
    volumes:
      - wp-data:/var/www/html
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  nginx:
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  volumes:
    wp-data:
      driver_opts:
        o: bind
        type: none
        device: /home/${USER}/data/wp-data
    db-data:
      driver_opts:
        o: bind
        type: none
        device: /home/${USER}/data/db-data

  networks:
    inception:
        driver: bridge
